---
- name: Common-vms --> Disable SELinux for testing ease
  lineinfile:
    dest:   /etc/selinux/config
    regexp: "^SELINUX=.*"
    line:   "SELINUX=disabled"
  sudo: yes 
  when: disable_selinux

- name:   Common-vms --> Creating groups
  group:  name={{ stack_user_group }} state=present gid={{ stack_user_group_gid }}

- name: Common-vms --> Create usenet user
  user: name={{ stack_user }} state=present uid={{ stack_user_uid }} group={{ stack_user_group }}

- name: Common-vms --> Install EPEL repo
  yum:  name=epel-release state=latest update_cache=yes

- name: Common-vms --> RPMFusion Repo
  yum:  name=http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm state=present update_cache=yes

- name: Common-vms --> Install common packages
  yum:  pkg={{ item }} state=installed
  with_items:
    - git
    - wget
    - nfs-utils
    - nfs-utils-lib
    - zip
    - unzip
    - python-pip

- name:   Common-vms --> NFS mount
  mount:  name={{ nfs_target }} src={{ nfs_source }} fstype={{ nfs_type }} opts={{ nfs_opts }} state=mounted
