---
- name: Add Conky-Manager PPA
  apt_repository: repo='ppa:teejee2008/ppa'
  
- name: Install
  apt: pkg={{item}} state=installed  update_cache=yes
  with_items:
        - conky
        - conky-manager

- name: Remove default ConkyManager Settings
  file: {{ conky_config_file }} state=absent
  ignore_errors: yes
  when: conky_use_backup

- name: Symlink ConkyManager Settings
  file: dest={{ conky_config_file }} src={{ conky_backup_file }} state=link
  when: conky_use_backup
