---
- name: Update sources
  apt: update_cache=yes
  
- name: Login Script --> Create Dir
  file: dest=/opt/misc state=directory
  sudo: yes
  
- name: Login Script --> Create and Populate Script
  lineinfile:
    dest: /opt/misc/login-setup.sh
    state: present
    regexp: "^%wheel"
    line: "#!/usr/bin/env bash\n\nxset led\nnumlockx on"
    create: yes
    mode: "a+x"
  sudo: yes 

- name: Set Greeter Script
  lineinfile:
    dest: /usr/share/lightdm/lightdm.conf.d/50-unity-greeter.conf
    line: "greeter-setup-script=/opt/misc/login-setup.sh"
  sudo: yes

# Install extra Themes/Icons
- name: Rave-X Icons --> Add ppa
  apt_repository: repo='ppa:ravefinity-project/ppa'
  
- name: Rave-X Icons --> Install
  apt: pkg={{item}} state=installed  update_cache=yes
  with_items:
        - rave-x-colors-icons
