---
- name: SickRage --> RPMFusion Repo
  yum:  name=http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm state=present update_cache=yes

- name: SickRage --> Add repo
  copy: src=SABnzbd.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name:     SickRage --> Install prerequisites for SAB
  command:  yum -y install wget git par2cmdline p7zip unrar unzip python-yenc python-feedparser python-configobj python-cheetah python-dbus python-support pyOpenSSL

- name:    SickRage --> Create dirs 
  command: mkdir -p /apps/data/.sabnzbd

- name:     SickRage --> Clone repo
  command:  git clone https://github.com/sabnzbd/sabnzbd.git /apps/sabnzbd

- name:     SickRage --> Take ownership of apps
  command:  chown -R {{ stack_user }}:{{ stack_user_group }} /apps

- name: SickRage --> SAB service
  copy: src=sabnzbd.service
        dest=/etc/systemd/system/
        owner=root group=root mode=0644

# - name: SickRage --> Copy ini file
#   copy: src=sabnzbd_config.ini
#         dest=/apps/data/.sabnzbd/sabnzbd_config.ini

- name:     SickRage --> enable SAB service
  command:  systemctl enable sabnzbd.service
