---
# - name: Install Dependencies
#   command: pip install lxml
#   sudo: yes

- name: Create dirs 
  file: path={{ couchpotato_config_dir }} owner={{ stack_user }}
        group={{ stack_user_group }} recurse=yes state=directory

- name: Clone repo from GitHub
  git:  repo={{ couchpotato_git_repo }}
        dest={{ couchpotato_install_dir }}
        version=master

- name: Restore Backup --> Extract archive
  unarchive:
    src: "{{ couchpotato_restore_file }}"
    dest: "{{ couchpotato_config_dir }}"
    copy: no
  sudo: yes
  when: couchpotato_restore_file is defined

- name: Set dir owner
  file: path={{ install_dir }} owner={{ stack_user }}
        group={{ stack_user_group }} recurse=yes
        state=directory mode=755

- name: Enable port on firewall
  command: "{{ item }}"
  with_items:
    - firewall-cmd --permanent --add-port=5050/tcp  # HTTP port
    - firewall-cmd --permanent --add-port=5222/tcp  # HTTPS port
    - firewall-cmd --reload
  sudo: yes
  when: firewall_enabled

- name: Add service
  template: src=couchpotatoserver.service.j2
            dest=/etc/systemd/system/couchpotatoserver.service
            owner=root group=root mode=0644

- name:     Enable service
  service:  name=couchpotatoserver.service enabled=yes state=started

- name: Stat backup target
  stat: path={{ couchpotato_backup_target }}
  register: backup_dir

- name: Create backup dir
  file: path={{ couchpotato_backup_target }} state=directory
        owner=root group=root
  when: backup_dir.stat.exists == False

- name: Stat backup script dir
  stat: path={{ couchpotato_backup_script_dir }}
  register: backup_script_dir

- name: Create backup script dir
  file: path={{ couchpotato_backup_script_dir }} state=directory
        owner=root group=root
  when: backup_script_dir.stat.exists == False

- name: Create backup script
  template: src=couchpotatoserver_backup.sh.j2
            dest="{{ couchpotato_backup_script_dir }}/couchpotatoserver_backup.sh"
            owner=root group=root mode="a+x"

- name: Create cron backup
  cron: name="Couch Potato Server Backup"
        hour="04" minute="00"
        user="root" job="{{ couchpotato_backup_script_dir }}/couchpotatoserver_backup.sh"
        state=present
