---
- name: CouchPotato --> Create dirs 
  file: path=/apps/data/.couchpotatoserver owner={{ stack_user }}
        group={{ stack_user_group }} recurse=yes
        state=directory
        
- name: CouchPotato --> Clone repo from GitHub
  git:  repo=https://github.com/RuudBurger/CouchPotatoServer.git
        dest=/apps/couchpotatoserver
        version=master

- name: CouchPotato --> Set dir owner
  file: path=/apps/couchpotatoserver owner={{ stack_user }}
        group={{ stack_user_group }} recurse=yes
        state=directory

- name: CouchPotato --> Add service
  copy: src=couchpotatoserver.service
        dest=/etc/systemd/system/
        owner=root group=root mode=0644

- name:     CouchPotato --> Enable service
  service:  name=couchpotatoserver.service enabled=yes state=started
