---
#- name: Ubuntu 14 install
#  include: "ubuntu14.yml"
#  when: ansible_distribution == "Ubuntu" AND ansible_distribution_major_version == "14"
#
#- name: Ubuntu 15 install
#  include: "ubuntu15.yml"
#  when: ansible_distribution == "Ubuntu" AND ansible_distribution_major_version == "15" AND cinnamon3 is not defined

- name: Ubuntu 15 install
  include: "ubuntu15_cinnamon3.yml"
#  when: ansible_distribution == "Ubuntu" AND ansible_distribution_major_version == "15" AND cinnamon3 is defined
# Ubuntu Greeter Reference: https://wiki.ubuntu.com/LightDM#Change_the_Default_Session
