---
- name: Install dependencies
  apt: pkg={{ item }} state=installed
  with_items:
    - python-gpgme

- name: Install deb
  apt: deb={{ dropbox_link }}
  sudo: yes

# No longer working ;(
# - name: Install the deamon
#   shell: "dropbox start -i"
