---
- name: Disable SELinux for testing ease
  lineinfile:
    dest:   /etc/selinux/config
    regexp: "^SELINUX=.*"
    line:   "SELINUX=disabled"
  sudo: yes 
  when: disable_selinux

- name: Install EPEL repo
  yum:  name=epel-release state=latest update_cache=yes

- name: RPMFusion Repo
  yum:  name=http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm state=present update_cache=yes

- name: Install common packages
  yum:  pkg={{ item }} state=installed update_cache=yes
  with_items:
    - git
    - wget
    - nfs-utils
    - nfs-utils-lib
    - zip
    - unzip
    - python-pip
