---
- name: Install with plugins
  apt: pkg={{item}} state=installed
  with_items:
        - remmina
        - libfreerdp-plugins-standard
        - remmina-plugin-vnc
        - remmina-plugin-rdp
        - remmina-plugin-gnome
