---
# Creates src dir
- name: Create .dotfiles dir
  file: path="{{ dotfiles_dir }}" state=present

# Clone repo to: ~/.dotfiles
- name: Clone dotfiles repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dir }}"

# Run installer
- name:   Run .dotfiles installer
  shell:  "{{ dotfiles_installer }}"
