---
# Enabled --> Configure
- name:     Enable and Start
  service:  name=firewalld.service enabled=yes state=started
  when:     firewall_enabled == true

# Disabled
- name:     Disable
  service:  name=firewalld.service enabled=no state=stopped
  when:     firewall_enabled == false
