---
- name: Install Requirements
  yum: pkg={{ item }} state=installed
  with_items:
    - python-cheetah
    - python-setproctitle
    
- name: Install Dependencies w/ pip
  command: pip install pyopenssl

- name: Clone repo from GitHub
  git:  repo={{ sickrage_repo }}
        dest="{{ sickrage_install_dir }}"
        version=master

- name: Create data dir
  file: path="{{ sickrage_config_dir }}" owner={{ stack_user }}
        group={{ stack_user_group }} recurse=yes
        state=directory mode=755

- name: Restore Backup --> Extract archive
  unarchive:
    src: "{{ sickrage_restore_file }}"
    dest: "{{ sickrage_config_dir }}"
    copy: no
  sudo: yes
  when: sickrage_restore_file is defined

- name: Set dir owner
  file: path={{ install_dir }} owner={{ stack_user }}
        group={{ stack_user_group }} recurse=yes
        state=directory mode=755

- name: Enable port on firewall
  command: "{{ item }}"
  with_items:
    - firewall-cmd --permanent --add-port=8081/tcp  # HTTP port
#    - firewall-cmd --permanent --add-port=9090/tcp  # HTTPS port
    - firewall-cmd --reload
  sudo: yes
  when: firewall_enabled

- name: Add service
  template: src=sickrage.service.j2
            dest=/etc/systemd/system/sickrage.service
            owner=root group=root mode=0644

- name:     Enable service
  service:  name=sickrage.service enabled=yes state=started

- name: Stat backup target
  stat: path={{ sickrage_backup_target }}
  register: backup_dir

- name: Create backup dir
  file: path={{ sickrage_backup_target }} state=directory
        owner=root group=root
  when: backup_dir.stat.exists == False

- name: Stat backup script dir
  stat: path={{ sickrage_backup_script_dir }}
  register: backup_script_dir

- name: Create backup script dir
  file: path={{ sickrage_backup_script_dir }} state=directory
        owner=root group=root
  when: backup_script_dir.stat.exists == False

- name: Create backup script
  template: src=sickrage_backup.sh.j2
            dest="{{ sickrage_backup_script_dir }}/sickrage_backup.sh"
            owner=root group=root mode="a+x"

- name: Create cron backup
  cron: name="SickRage Backup"
        hour="04" minute="20"
        user="root" job="{{ sickrage_backup_script_dir }}/sickrage_backup.sh"
        state=present
