---
- name: Install Requirements
  yum: pkg={{ item }} state=installed
  with_items:
    - python-cheetah
    - python-setproctitle
    
- name: Install Dependencies w/ pip
  command: pip install pyopenssl

- name: Clone repo from GitHub
  git:  repo=https://github.com/SickRage/SickRage.git
        dest=/apps/sickrage
        version=master

- name: Set dir/data owner
  file: path=/apps/data/.sickrage owner={{ stack_user }}
        group={{ stack_user_group }} recurse=yes
        state=directory mode=755

- name: Restore Backup --> Copy archive
  copy: src={{ sickrage_backup_path }} dest=/apps/data
        owner={{ stack_user }} group={{ stack_user_group }}
  when: sickrage_backup_path is defined
  
- name: Restore Backup --> Extract archive
  unarchive:
    src: /apps/data/sickrage_backup.zip
    dest: /apps/data/.sickrage
    copy: no
  sudo: yes
  when: sickrage_backup_path is defined

- name: Set dir owner
  file: path=/apps owner={{ stack_user }}
        group={{ stack_user_group }} recurse=yes
        state=directory mode=755

- name: Add service
  copy: src=sickrage.service
        dest=/etc/systemd/system/
        owner=root group=root mode=0644

- name:     Enable service
  service:  name=sickrage.service enabled=yes state=started



# Backed Up Files: cache.db sickrage_config.ini failed.db sickbeard.db cache
# Used Command: zip -9 -q -r sickrage-`date \+%Y\%m\%d-%T`.zip cache.db sickrage_config.ini failed.db sickbeard.db cache

# zip -v -r sickrage-`date \+%Y\%m\%d`.zip cache.db config.ini failed.db sickbeard.db cache
# zip -9 -q -r sickrage-`date \+%Y\%m\%d-%T`.zip cache.db sickrage_config.ini failed.db sickbeard.db cache