---
- name: Add repo key
  apt_repository: repo='ppa:webupd8team/java'
  
- name: Bypass Oracle Popup Window
  shell: "echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections && echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections"
  sudo: yes
  
- name: Install
  apt: pkg=oracle-java8-installer state=installed update_cache=yes