---
- name: Create mount dir
  file: path={{ nfs_mount_root_dir }}
        state=directory
        owner={{ os_username }} group={{ os_username }}
  sudo: yes
  when: nfs_server is defined

- name:   NFS mounts
  mount:  name={{ nfs_mount_root_dir }}/{{ item.value.name }}
          src={{ item.value.source }}
          fstype={{ item.value.type }}
          opts={{ item.value.opts }}
          state=mounted
  with_dict: "{{ nfs_shares }}"
  sudo: yes
  when: nfs_server is defined
