---
- name: Check if installed
  stat: path=/opt/whatpulse/whatpulse
  register: file_check

- name: Ubuntu install
  include: "ubuntu.yml"
  when: ansible_distribution in [ "Ubuntu", "Linuxmint" ] and file_check.stat.exists == False
