---
- name: WhatPulse --> Check if installed
  stat: path=/opt/whatpulse/whatpulse
  register: file_check

- name: WhatPulse --> Ubuntu install
  include: "ubuntu.yml"
  when: ansible_distribution == 'Ubuntu' and file_check.stat.exists == False
