---
- name: Download archive
  get_url:
    url: "{{ whatpulse_link }}"
    dest: "{{ whatpulse_dl_path }}"
    validate_certs: False
  register: what_pulse_downloaded
  
- name: Creates install directory
  file: path=/opt/whatpulse state=directory recurse=yes
  
- name: Extract archive
  unarchive:
    src: "{{ whatpulse_dl_path }}"
    dest: "/opt/whatpulse/"
    copy: no
  sudo: yes
  when: what_pulse_downloaded|changed
  
- name: Install dependencies
  apt: pkg={{item}} state=installed
  with_items:
        - openssl
        - libqtcore4
        - libqtwebkit4
        - libqt4-sql
        - libqt4-sql-sqlite
        - libssl-dev
        - libqtscript4-core
        - libqtscript4-gui
        - libqtscript4-network
        - libqtscript4-webkit
        - libpcap0.8
        - libpcapnav0
  
- name: netcp setup
  shell: setcap cap_net_raw,cap_net_admin=eip /opt/whatpulse/whatpulse
  sudo: yes
  
- name: Copy My Interactive Permissions Setup Script
  copy:
    src: setup-input-permissions-enhanced.sh
    dest: /opt/whatpulse/setup-input-permissions-enhanced.sh
    mode: "a+x"
  
- name: Input Permissions Setup (Non-Interactive)
  shell: /opt/whatpulse/setup-input-permissions-enhanced.sh true {{os_username}}
  sudo: yes
  
- name: Symlink executable
  file:
    src: /opt/whatpulse/whatpulse 
    dest: /usr/local/bin/whatpulse
    state: link
  sudo: yes

- name: Remove archive
  file:
    path: "{{ whatpulse_dl_path }}"
    state: absent

- name: Desktop File
  copy:
    src: whatpulse.desktop
    dest: /usr/share/applications/whatpulse.desktop
    mode: 0644
