---
# Ubuntu vars
common_install_os_utils: true
common_install_filesys_utils: true
common_install_archive_utils: true
common_install_common_utils: true
common_install_media: true
common_install_dev_utils: true
common_install_hw_apps: true
common_install_av: true
common_install_printer_scanners: true
