---
- name: Download archive
  get_url:
    url: "{{ vs_code_link }}"
    dest: "{{ vs_code_dl_path }}"
    validate_certs: False
  register: vs_code_downloaded
  
- name: Extract archive
  unarchive:
    src: "{{ vs_code_dl_path }}"
    dest: "/opt/"
    copy: no
  sudo: yes
  when: vs_code_downloaded|changed
  
- name: Symlink executable
  file:
    src: /opt/VSCode-linux-x64/code 
    dest: /usr/local/bin/code
    state: link
  sudo: yes

- name: Desktop File
  copy:
    src: code.desktop
    dest: /usr/share/applications/code.desktop
    mode: 0644
 
- name: Settings PreReq
  file: path=/home/{{ os_username }}/.config/Code/User state=directory

- name: Symlink Settings
  file: dest=/home/{{ os_username }}/.config/Code/User/settings.json
        src={{ backup_dir_root }}/configs/VSCode/settings.json
        state=link

- name: Extension PreReq
  file: path=/home/{{ os_username }}/.vscode state=directory

- name: Extensions Symlink
  file: dest=/home/{{ os_username }}/.vscode/extensions
        src={{ backup_dir_root }}/configs/VSCode/extensions
        state=link
