---
- hosts: [stack]
  gather_facts: yes
  become: true
  vars:
    os_username: usenet
    install_dir: /apps
    selinux_enabled: false
    firewall_enabled: false
    ssl_dir: "{{ install_dir }}/ssl"
    backup_dir_root: /mnt/backup

    nfs_backup_target: "{{ nfs_mount_root_dir }}/backup"
    
    sab_restore_file: "{{ backup_dir_root }}/configs/vms-stack/sabnzbd_backup.tar.gz"
    sab_backup_target: "{{ nfs_backup_target }}"
    
    sickrage_restore_file: "{{ backup_dir_root }}/configs/vms-stack/sickrage_backup.tar.gz"
    sickrage_backup_target: "{{ nfs_backup_target }}"
    
    stack_user: "{{ os_username }}"
    stack_password: welcome1
    stack_user_uid: 1020
    stack_user_group: "{{ os_username }}"
    stack_user_group_gid: 1020

    mysql_root_password: welcome1
    stack_mysql_root_password: welcome1
    guac_sql_password: welcome1
  
  vars_files:
    - vars/stack/nfs-mounts.yml
    - vars/stack/couchpotato.yml

  pre_tasks:
    - shell:  echo "Starting..."

    - name:   Create group
      group:  name={{ stack_user_group }}
              state=present
              gid={{ stack_user_group_gid }}

    - name: Create user
      user: name={{ stack_user }}
            state=present
            uid={{ stack_user_uid }}
            group={{ stack_user_group }}

  roles:
    - patrick-hill.common
    - patrick-hill.nfs-mounts
    - patrick-hill.firewall
    - patrick-hill.openssl
    - patrick-hill.sabnzbd          # port 8080
    - patrick-hill.sickrage         # port 8081
    - patrick-hill.couchpotato      # port 5050
    - patrick-hill.plexmediaserver  # Port 32400/web/index.html#
    - patrick-hill.headphones       # port 8181
    - patrick-hill.sonarr           # port 8989
    # In Development 
    # - patrick-hill.transmission  # port 
    # - patrick-hill.guacamole # Port 8080/8443 
    # Ideas
    # - subsonic
    # - owncloud
    
  post_tasks:
    #  - name: Reboot system
    #    raw: /sbin/shutdown -r 0
    #    sudo: yes
    #   changed_when: True
  