---
- hosts: quantum
  gather_facts: yes
  sudo: true
  vars:
    git_user_name: "Patrick Hill"
    git_user_email: "Hill@HillsPCWorld.com"
    dropbox_link: https://linux.dropbox.com/packages/ubuntu/dropbox_2015.10.28_amd64.deb
    dropbox_dl_path: /tmp/dropbox.deb
    # vs_code_link: https://code.visualstudio.com/Docs/?dv=linux64
    vs_code_link: https://go.microsoft.com/fwlink/?LinkID=620884
    vs_code_dl_path: /tmp/vs-code.zip
    whatpulse_link: http://whatpulse.org/downloads/257/64bit/
    whatpulse_dl_path: /tmp/what-pulse.tar.gz
    intellij_link: https://download.jetbrains.com/idea/ideaIC-15.0.4.tar.gz
    intellij_dl_path: /tmp/intellij.tar.gz
    vagrant_link: https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb
    vagrant_dl_path: /tmp/vagrant.deb
    packer_link: https://releases.hashicorp.com/packer/0.9.0/packer_0.9.0_linux_amd64.zip
    packer_dl_path: /tmp/packer.zip
    vmware_link: 
    vmware_dl_path: "/home/phill/Desktop/src/VMware-Workstation-Full-12.1.0-3272444.x86_64.bundle"
    vmware_serial_param: ""
    # vmware_serial_param: "--set-setting vmware-workstation serialNumber XXXXX-XXXXX-XXXXX-XXXXX-XXXXX"

  pre_tasks:
    - shell: echo 'Starting...'
  
  roles:
    - common
    - cinnamon-desktop
    - chrome
    - dropbox
    - jdk8
    - vs-code
    - what-pulse
    - remmina
    - intellij
    - vagrant
    - packer
    - conky
    # - vmware
    
  post_tasks:
    - shell: echo 'Done'
  
    # - name: Reboot system
    #   raw: /sbin/shutdown -r 1
    #   changed_when: True
  
  # If we need to use this server again after restart, use below...
  # - name: Wait for system to complete reboot (5 min max / 90 sec delay)
  #   wait_for: host=quantum port=22 timeout=300 delay=90 state=started
  #   delegate_to: 127.0.0.1
  #   ignore_errors: yes