---
- hosts: stack
  gather_facts: yes
  sudo: true
  vars:
    disable_firewall: true
    disable_selinux: true
    stack_user: usenet
    stack_password: welcome1
    stack_user_uid: 1020
    stack_user_group: usenet
    stack_user_group_gid: 1020
    nfs_source: 10.0.0.150:/mnt/R6-18TB/Hills_Shared/dataset_files/Media
    nfs_target: /mnt/Media
    nfs_type: nfs4
    nfs_opts: rw,hard,intr
    ssl_dir: /apps/ssl
    ssl_key_password: welcome1
    
  pre_tasks:
    - shell:  echo "Starting..."
            
  roles:
    - common-vms
    - openssl
    - sabnzbd
    # - sickrage
    
  post_tasks:
    - name: Reboot system
      raw: /sbin/shutdown -r 0
      sudo: yes
      changed_when: True
  