---
- hosts: [stack,test]
  gather_facts: yes
  sudo: true
  vars:
    install_dir: /apps
    firewall_enabled: false
    # firewall_enable_services:
    #   - http
    #   - https
    disable_selinux: true
    stack_user: usenet
    stack_password: welcome1
    stack_user_uid: 1020
    stack_user_group: usenet
    stack_user_group_gid: 1020
    nfs_shares:
      media:
          source: 10.0.0.150:/mnt/R6-18TB/Hills_Shared/dataset_files/Media
          target: /mnt/media
          type: nfs4
          opts: rw,hard,intr,rsize=8192,wsize=8192
      backup:
          source: 10.0.0.150:/mnt/R6-18TB/Hills_Shared/dataset_files/Backups/Computers/vms
          target: /mnt/backup/
          type: nfs4
          opts: rw,hard,intr,rsize=8192,wsize=8192
    ssl_dir: "{{ install_dir }}/ssl"
    ssl_key_password: welcome1
    sab_config_path: /home/phill/Dropbox/0-Backups/configs/vms-stack/sabnzbd_config.ini
    sickrage_backup_path: /home/phill/Dropbox/0-Backups/configs/vms-stack/sickrage_backup.zip
    couchpotato_backup_path: /home/phill/Dropbox/0-Backups/configs/vms-stack/couchpotato_backup.zip
    mysql_root_password: welcome1
    stack_mysql_root_password: welcome1
    guac_sql_password: welcome1
    
  pre_tasks:
    - shell:  echo "Starting..."
    
  roles:
    - common-vms
    - firewall
    - openssl
    - sabnzbd       # port 8080
    - sickrage      # port 8081
    - couchpotato   # port 5050
    # - headphones    # port 8181
    # - sonarr        # port 8989
    # - transmission  # port 
    # http://geekyadmins.com/install-transmission-on-centos-7/
    # https://elijahpaul.co.uk/script-install-for-transmission-2-83-seedbox-on-centos-6-5/
    - guacamole # Override 'mysql_root_password' w/ stack_mysql_root_password

    # - plex
    # - subsonic
    # - owncloud
    
    
  post_tasks:
    - name: Playbook --> Dir --> Set Owner
      file: dest={{ install_dir }} owner={{ stack_user }}
            group={{ stack_user_group }} recurse=yes
    
    # - name: Reboot system
    #   raw: /sbin/shutdown -r 0
    #   sudo: yes
    #   changed_when: True
  