---
- hosts: [stack]
  gather_facts: yes
  sudo: true
  vars:
    disable_selinux: true #common-vms
    os_username: usenet
    install_dir: /apps
    ssl_dir: "{{ install_dir }}/ssl"
    backup_dir_root: /home/phill/Dropbox/0-Backups
    nfs_server: 10.0.0.150
    nfs_backup_target: "{{ nfs_mount_root_dir }}/{{ nfs_shares.backup.name }}"
    sab_restore_file: "{{ backup_dir_root }}/configs/vms-stack/sabnzbd_backup.tar.gz"
    couchpotato_restore_file: "{{ backup_dir_root }}/configs/vms-stack/couchpotato_backup.zip"

    firewall_enabled: false
    # firewall_enable_services:
    #   - http
    #   - https
    stack_user: usenet
    stack_password: welcome1
    stack_user_uid: 1020
    stack_user_group: usenet
    stack_user_group_gid: 1020

    nfs_mount_root_dir: /mnt
    nfs_shares:
      media:
          name: media
          source: 10.0.0.150:/mnt/R6-18TB/Hills_Shared/dataset_files/Media
          type: nfs4
          opts: rw,hard,intr,rsize=8192,wsize=8192
      backup:
          name: backup
          source: 10.0.0.150:/mnt/R6-18TB/Hills_Shared/dataset_files/Backups/vms
          type: nfs4
          opts: rw,hard,intr,rsize=8192,wsize=8192

    sab_config_path: "{{ backup_dir_root }}/configs/vms-stack/sabnzbd_config.ini"
    sickrage_backup_path: "{{ backup_dir_root }}/configs/vms-stack/sickrage_backup.zip"
    mysql_root_password: welcome1
    stack_mysql_root_password: welcome1
    guac_sql_password: welcome1
    
  pre_tasks:
    - shell:  echo "Starting..."
    #    Verify Ansible Version
    - assert:
        that: ansible_version.major > 1

    - name:   Create group
      group:  name={{ stack_user_group }} state=present gid={{ stack_user_group_gid }}

    - name: Create user
      user: name={{ stack_user }} state=present uid={{ stack_user_uid }} group={{ stack_user_group }}

  roles:
    - common
    - nfs-mounts
    - firewall
    - openssl
    - sabnzbd       # port 8080
#    - sickrage      # port 8081
    - couchpotato   # port 5050
    # - headphones    # port 8181
    # - sonarr        # port 8989
    # - transmission  # port 
    # http://geekyadmins.com/install-transmission-on-centos-7/
    # https://elijahpaul.co.uk/script-install-for-transmission-2-83-seedbox-on-centos-6-5/
#    - guacamole # Override 'mysql_root_password' w/ stack_mysql_root_password
    # - plex
    # - subsonic
    # - owncloud
    
    
#  post_tasks:
#    - name: Playbook --> Dir --> Set Owner
#      file: dest={{ install_dir }} owner={{ stack_user }}
#            group={{ stack_user_group }} recurse=yes
    
    # - name: Reboot system
    #   raw: /sbin/shutdown -r 0
    #   sudo: yes
    #   changed_when: True
  