---
#- hosts: eventhorizon
- hosts: localhost
  gather_facts: yes
  sudo: true
  vars:
    os_username:    'phill'
    backup_dir_root: /home/phill/Dropbox/0-Backups
    git_user_name:  "Patrick Hill"
    git_user_email: "Hill@HillsPCWorld.com"

  pre_tasks:
    - shell: echo 'Starting...'
    
  roles:
    - common
    - nfs-mounts
    - what-pulse
    - chrome
    - remmina
    - vagrant
    - packer
    - virtualbox
    - ssh-server

  post_tasks:
    - shell: echo 'Done'

