---
- hosts: stack
  gather_facts: no
  sudo: true
  vars:
    - password: $6$rounds=656000$B/OzGPN5bfVkA8l9$yAKugT8qHocV7DmqzaMZSMzkwRgNO2j8H0tQaCyQIDottPgT8lZKHoXSZLZTX9o9d4c7qbS50DBC8wfCh3K0g1

  pre_tasks:
    - name:     Disable Firewall :)
      command:  systemctl disable firewalld.service && systemctl stop firewalld.service
      
    - name:     Create usenet user
      user:     name=usenet
      
      # yum -y install nfs-utils autofs
      # mkdir /Hills_Shared
      # echo "/Hills_Shared /etc/auto.hills-shared --timeout=600 --ghost" > /etc/auto.master
      # echo "Hills_Shared -fstype=nfs,rw 10.0.0.150:/Hills_Shared" > /etc/auto.hills-shared
      # service autofs restart
      # chkconfig autofs on
      # 
      
  roles:
    - common-vms
    - openssl
    - sabnzbd
    # - sickrage
    
  post_tasks:
    - name: Reboot system
      raw: /sbin/shutdown -r 1
      changed_when: True
  