---
- hosts: stack
  gather_facts: yes
  sudo: true
  vars:
    firewall_enabled: false
    # firewall_enable_services:
    #   - http
    #   - https
    disable_selinux: true
    stack_user: usenet
    stack_password: welcome1
    stack_user_uid: 1020
    stack_user_group: usenet
    stack_user_group_gid: 1020
    nfs_source: 10.0.0.150:/mnt/R6-18TB/Hills_Shared/dataset_files/Media
    nfs_target: /mnt/Media
    nfs_type: nfs4
    nfs_opts: rw,hard,intr
    ssl_dir: /apps/ssl
    ssl_key_password: welcome1
    sab_config_path: /home/phill/Dropbox/0-Backups/configs/vms-stack/sabnzbd_config.ini
    
  pre_tasks:
    - shell:  echo "Starting..."
            
  roles:
    - common-vms
    - firewall
    - openssl
    - sabnzbd       # port 8080
    - sickrage      # port 8081
    - couchpotato   # port 5050
    - headphones    # port 8181
    - sonarr        # port 8989
    # - transmission  # port 
    # http://geekyadmins.com/install-transmission-on-centos-7/
    # https://elijahpaul.co.uk/script-install-for-transmission-2-83-seedbox-on-centos-6-5/
    # - guacamole

    # - plex
    # - subsonic
    # - owncloud
    
    
  post_tasks:
    - name: Playbook --> Dir --> Set Owner
      file: dest=/apps owner={{ stack_user }}
            group={{ stack_user_group }} recurse=yes
    
    - name: Reboot system
      raw: /sbin/shutdown -r 0
      sudo: yes
      changed_when: True
  