---
- name: Virtualbox --> Add repo key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present
  sudo: yes

- name: Virtualbox --> Add to source
  lineinfile:
    dest: /etc/apt/sources.list.d/virtualbox.list
    line: "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian stable contrib"
    create: yes
    mode: 0644
  sudo: yes

- name: Virtualbox --> Install
  apt: 
    pkg: virtualbox-5.0
    state: installed
    update_cache: yes
  